### ISSUE TITLE
Replying to a thread makes all the nested comments look like the top comment

### ISSUE THREAD

**Issue by bugthug** [wpd-world/wpd-world#4]
[Video](https://srv-file1.gofile.io/download/zAAwod/946ce1ac9fcd1213c82025c749d1d61d/72cb0e6f61e7471890a43e67caa0dcf8-1-.mp4)

**Comment by kitsunedayo** [comment]
I can't view the video

![image](https://user-images.githubusercontent.com/48719029/54666328-0fef0180-4b1c-11e9-9388-afae90a9461c.png)

Can you describe the issue? I'm assuming that posting a reply will destroy the nested comment structure, and it's fixed when the page is reloaded. Is that right?

**Comment by bugthug** [comment]
Sorry, I think [this link](https://streamable.com/lnn5k) will work.
