### ISSUE TITLE
Comment replys get shorter until unreadable

### ISSUE THREAD

**Issue by bugthug** [wpd-world/wpd-world#6]
Comments get shorter
![](https://cdn.discordapp.com/attachments/556935512926191647/557242630162087948/Screenshot_20190318-181538_Chrome.png)
until unreadable
![](https://cdn.discordapp.com/attachments/556935512926191647/557242778275545098/Screenshot_20190318-181549_Trebuchet.png)

**Comment by bugthug** [comment]
The problem also occurs in pcs with low resolution

**Comment by kitsunedayo** [comment]
Somewhat fixed in https://github.com/wpd-world/wpd-world/commit/5b69163040ad7fbcf70f57bad01a3f36146c15e3. I've reduced the left padding and removed the right padding.
