### ISSUE TITLE
Reddit-like ranking algorithm

### ISSUE THREAD

**Issue by bugthug** [wpd-world/wpd-world#7]
Currently, posts are ranked by how new they are, regardless of how popular they are.

[This article](https://medium.com/hacking-and-gonzo/how-reddit-ranking-algorithms-work-ef111e33d0d9) explains how Reddit sorts comment by hot in a very practical sense. (exploring the algorithm by actually looking at the code and not just stating observations). it should be a great start.

**Comment by kitsunedayo** [comment]
Implemented a basic version of it. SQLite doesn't have a built-in log function, so I'm using linear for now. I'll figure something out later.
